export default function sitemap() {
  return [
    { url: 'https://devtimize.com', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/services', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/projects', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/about', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/contact', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/ai-receptionist', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/hvac-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/dentist-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/lawyer-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/medspa-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/roofing-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/plumber-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/industries/restaurant-websites', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/how-to-build-trading-bot-python', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/rag-vs-fine-tuning-chatbots', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/flutter-vs-react-native-2025', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/how-much-does-chatbot-cost', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/hire-developer-from-pakistan', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/best-tech-stack-saas-2025', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/restaurant-website-that-books-reservations', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/why-restaurants-need-professional-website-2026', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/ai-receptionist-for-hvac-companies', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/how-much-does-dentist-website-cost-uk-us', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/ai-receptionist-for-small-business-2026-guide', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/ai-receptionist-for-clinics-medical-practices', lastModified: new Date('2026-05-01') },
    { url: 'https://devtimize.com/blog/hire-developer-pakistan-complete-vetting-guide', lastModified: new Date('2026-05-01') },
  ]
}
